//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quest
    {
        public Quest()
        {
            this.Votes = new HashSet<Vote>();
        }
    
        public int QuestId { get; set; }
        public int EmployeeId { get; set; }
        public int Year { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<Vote> Votes { get; set; }
    }
}
