//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PresentsApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vote
    {
        public int VoteId { get; set; }
        public int EmployeeId { get; set; }
        public int PresentId { get; set; }
        public int QuestId { get; set; }
    
        public virtual Present Present { get; set; }
        public virtual Quest Quest { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
