<%@ Page Title="EditUsers" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="EditUsers.aspx.cs" Inherits="HambergiteConquistador.Admin.EditUsers" %>
<asp:Content ID="Content" ContentPlaceHolderID="MainContent" runat="server">

    <asp:GridView 
        ID="GridViewEditUsers"
        runat="server" 
        AllowPaging="true" 
        AllowSorting="true" 
        ItemType="HambergiteConquistador.Models.AspNetUser" 
        DataKeyNames="Id" 
        SelectMethod="GridViewEditUsers_GetData" 
        AutoGenerateColumns="false" 
        UpdateMethod="GridViewEditUsers_UpdateItem" 
        DeleteMethod="GridViewEditUsers_DeleteItem"
        CssClass="text-center container well" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">


        <Columns>

            <asp:BoundField HeaderText="Username" SortExpression="Username" DataField="UserName" />
            <asp:BoundField HeaderText="Score" SortExpression="Score" DataField="Score" />
            <asp:BoundField HeaderText="Bonus Point" SortExpression="Bonus" DataField="Bonus" />
            
        

            <asp:HyperLinkField runat="server" DataNavigateUrlFormatString="~/Admin/UpdateUserRoles.aspx?userName={0}" DataNavigateUrlFields="UserName"  Text="Update roles"></asp:HyperLinkField>
            <asp:HyperLinkField runat="server" DataNavigateUrlFormatString="~/Admin/ChangeUserPassword.aspx?userName={0}" DataNavigateUrlFields="UserName"  Text="Change Password"></asp:HyperLinkField>

        </Columns>
    </asp:GridView>
</asp:Content>